#@data/values-schema
---
api1Enabled: true
api1Url: /hoge
api1Method: put
api1Description: foo
api2Enabled: false
api2Url: ""
api2Method: ""
api2Description: ""
api3Enabled: true
api3Url: /hoge3
api3Method: put
api3Description: foo
api4Enabled: true
api4Url: /hoge4
api4Method: put
api4Description: foo
api5Enabled: true
api5Url: /hoge5
api5Method: put
api5Description: foo

version: 1.0.0

advParam1: hoge
advParam2: foo
